import { PaginatedResponse, Project } from "@/types/api";

// Mock data for development to avoid API calls
export const mockProjects: PaginatedResponse<Project> = {
  data: [
    {
      id: 1,
      documentId: "sample-1",
      name: "Sample Project 1",
      description: "A sample project for development",
      source_code_url: "https://github.com/example/project1",
      url: "https://project1.com",
      is_released: true,
      createdAt: "2024-01-01T00:00:00.000Z",
      updatedAt: "2024-01-01T00:00:00.000Z",
      publishedAt: "2024-01-01T00:00:00.000Z",
      created_at: "2024-01-01T00:00:00.000Z",
      categories: [{ name: "Web Development" }],
      types: [{ name: "Full Stack" }],
      platforms: [{ name: "Web" }],
      technologies: [{ name: "Next.js" }, { name: "TypeScript" }],
      thumbnail: {
        name: "sample-thumbnail.jpg",
        alternativeText: "Sample project thumbnail",
        caption: null,
        width: 800,
        height: 600,
        formats: {
          large: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "large",
            mime: "image/jpeg",
            name: "large",
            path: null,
            size: 100000,
            width: 800,
            height: 600,
            sizeInBytes: 100000,
          },
          small: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "small",
            mime: "image/jpeg",
            name: "small",
            path: null,
            size: 20000,
            width: 200,
            height: 150,
            sizeInBytes: 20000,
          },
          medium: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "medium",
            mime: "image/jpeg",
            name: "medium",
            path: null,
            size: 50000,
            width: 400,
            height: 300,
            sizeInBytes: 50000,
          },
          thumbnail: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "thumb",
            mime: "image/jpeg",
            name: "thumb",
            path: null,
            size: 10000,
            width: 100,
            height: 75,
            sizeInBytes: 10000,
          },
        },
        hash: "sample_hash",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 100000,
        url: "/placeholder.png",
        previewUrl: null,
        provider: "local",
      },
    },
    {
      id: 2,
      documentId: "sample-2",
      name: "Sample Project 2",
      description: "Another sample project for development",
      source_code_url: "https://github.com/example/project2",
      url: "https://project2.com",
      is_released: true,
      createdAt: "2024-01-02T00:00:00.000Z",
      updatedAt: "2024-01-02T00:00:00.000Z",
      publishedAt: "2024-01-02T00:00:00.000Z",
      created_at: "2024-01-02T00:00:00.000Z",
      categories: [{ name: "Frontend" }],
      types: [{ name: "SPA" }],
      platforms: [{ name: "Web" }, { name: "Mobile" }],
      technologies: [{ name: "React" }, { name: "Tailwind" }],
      thumbnail: {
        name: "sample-thumbnail-2.jpg",
        alternativeText: "Sample project 2 thumbnail",
        caption: null,
        width: 800,
        height: 600,
        formats: {
          large: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "large2",
            mime: "image/jpeg",
            name: "large",
            path: null,
            size: 100000,
            width: 800,
            height: 600,
            sizeInBytes: 100000,
          },
          small: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "small2",
            mime: "image/jpeg",
            name: "small",
            path: null,
            size: 20000,
            width: 200,
            height: 150,
            sizeInBytes: 20000,
          },
          medium: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "medium2",
            mime: "image/jpeg",
            name: "medium",
            path: null,
            size: 50000,
            width: 400,
            height: 300,
            sizeInBytes: 50000,
          },
          thumbnail: {
            ext: ".jpg",
            url: "/placeholder.png",
            hash: "thumb2",
            mime: "image/jpeg",
            name: "thumb",
            path: null,
            size: 10000,
            width: 100,
            height: 75,
            sizeInBytes: 10000,
          },
        },
        hash: "sample_hash_2",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 100000,
        url: "/placeholder.png",
        previewUrl: null,
        provider: "local",
      },
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 9,
      pageCount: 1,
      total: 2,
    },
  },
};

export const shouldUseMockData =
  process.env.NODE_ENV === "development" &&
  process.env.USE_MOCK_DATA === "true";
