import type { Metadata } from "next";

// Assets
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

import { AppSidebar } from "@/components/app";
import { ResponsiveIndicator } from "@/components/atoms/responsive-indicator";
import { ThemeWrapper } from "@/components/atoms/theme-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} font-mono`}>
        <ThemeWrapper attribute="class" defaultTheme="dark" enableSystem>
          <div className="flex overflow-auto">
            <AppSidebar />
            <main className="flex-1 px-10 relative overflow-y-scroll">
              {children}
            </main>
          </div>
        </ThemeWrapper>
        <ResponsiveIndicator />
      </body>
    </html>
  );
}
